Game.cpp
MAX_LOADSTRING
Referenced by wWinMain.
HINSTANCE hInst
Referenced by InitInstance, WndProc.
WCHAR szTitle[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, wWinMain.
WCHAR szWindowClass[MAX_LOADSTRING][MAX_LOADSTRING]
Referenced by InitInstance, MyRegisterClass, wWinMain.
ATOM MyRegisterClass(HINSTANCE hInstance)
References IDC_GAME, IDI_GAME, IDI_SMALL, szWindowClass, WndProc.
Referenced by wWinMain.
BOOL InitInstance(HINSTANCE, int)
References hInst, szTitle, szWindowClass.
Referenced by wWinMain.
LRESULT CALLBACK WndProc(HWND, UINT, WPARAM, LPARAM)
References About, hInst, IDD_ABOUTBOX, IDM_ABOUT, IDM_EXIT.
Referenced by MyRegisterClass.
INT_PTR CALLBACK About(HWND, UINT, WPARAM, LPARAM)
Referenced by WndProc.
int APIENTRY wWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPWSTR lpCmdLine, _In_ int nCmdShow)
References IDC_GAME, IDS_APP_TITLE, InitInstance, MAX_LOADSTRING, MyRegisterClass, szTitle, szWindowClass.