Entity
std::list<std::shared_ptr<Component> > Entity::components
Referenced by Clear.
std::string Entity::name
Referenced by GetName, SetName.
size_t Entity::id
Referenced by GetId.
virtual Entity::~Entity()
const std::string Entity::GetName() const
References name.
void Entity::SetName(const std::string &newName)
References name.
void Entity::SetId(size_t newId)
Referenced by EntityManager< N >::EntityManager.
size_t Entity::GetId() const
References id.
Referenced by EntityManager< N >::Kill.
virtual void Entity::Update(float time)
virtual void Entity::Render(LPDIRECT3DDEVICE9 device)
void Entity::Clear()
References components.
Referenced by EntityManager< N >::Create.
void Entity::Add(T &t)